# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 209c7243381fe720b9588c396185ea799855fd57b240792b87e909c77d560c76714bbd46c044c1ee8786dde159a6951c51541307ef1a8f4f624b2b0a2d4bac7d

test:
  secret_key_base: 73f8b9b339639199433f539e6dc2e29f9c791802bd318eefbb53f748efad2bc987d4311c796aa86f638aeb34c83dcf59952155dd350efc37509e00890b56b193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
